apiVersion: v1
kind: Service
metadata:
  name: voting-service
  app: demo-voting-app
spec:
  type: LoadBalance
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app